# Generated by Django 3.0.8 on 2020-07-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='schooluser',
            name='name',
        ),
    ]
