# Generated by Django 3.0.8 on 2020-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200705_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='permissions',
            field=models.CharField(choices=[('administrator', 'Dyrektor'), ('teacher', 'Nauczyciel'), ('student', 'Uczeń')], max_length=15),
        ),
    ]
