# Generated by Django 3.0.8 on 2020-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200705_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
