# Generated by Django 3.0.8 on 2020-07-06 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
