# Generated by Django 3.0.8 on 2020-07-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_studenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='grades',
            field=models.CharField(default='', max_length=150),
        ),
    ]
