# Generated by Django 3.0.8 on 2020-07-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200710_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttest',
            name='answer_1_wrong',
        ),
        migrations.RemoveField(
            model_name='studenttest',
            name='answer_2_wrong',
        ),
        migrations.RemoveField(
            model_name='studenttest',
            name='answer_3_wrong',
        ),
        migrations.AddField(
            model_name='studenttest',
            name='answer_1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='answer_2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='answer_3',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='answer_4',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='answer_right',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5)),
                ('_passed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolUser')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StudentTest')),
            ],
        ),
    ]
