# Generated by Django 3.0.8 on 2020-07-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200711_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='_passed',
        ),
    ]
