# Generated by Django 3.0.8 on 2020-07-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_exam__passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
